export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
