// INGREDIENTS
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_START = 'GET_INGREDIENTS_START';
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL';

// ORDERS
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_START = 'GET_ORDERS_START';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';
export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_START = 'POST_ORDER_START';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';
export const GO_TO_ORDER = 'GO_TO_ORDER';

// AUTH
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
